### ISSUE TITLE
360 N4测试自定义case1和case9_ThreadMonitor不通过

### ISSUE THREAD

**Issue by Gordon0918** [tiann/epic#17]
case1和case9都是线程相关的，log一样，如下所示

01-09 17:15:44.560   330  2845 I BufferQueueProducer: [me.weishu.epic.samples/me.weishu.epic.samples.MainActivity](this:0x7f7bb94c00,id:655,api:1,p:19
297,c:330) queueBuffer: fps=2.79 dur=5736.25 max=5493.66 min=10.55

01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.art.entry.Entry64_2.referenceBridge(Entry64_2.java:401)
01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.art.entry.Entry64_2.referenceBridge(Entry64_2.java:317)
01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.samples.tests.custom.Case1.validate(Case1.java:54)
01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.samples.tests.TestManager$1.predicate(TestManager.java:187)
01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.samples.tests.TestCase.validate(TestCase.java:27)
01-09 17:15:53.063 19297 19297 E TestCase:      at me.weishu.epic.samples.MainActivity$MyAdapter$2.onClick(MainActivity.java:114)
01-09 17:15:53.068  1141  2610 I NotificationService: enqueueToast pkg=me.weishu.epic.samples callback=android.app.ITransientNotification$Stub$Proxy@d
8b67d2 duration=0
01-09 17:15:53.069  1141  2610 D NotificationService: Show pkg=me.weishu.epic.samples callback=android.app.ITransientNotification$Stub$Proxy@d8b67d2
01-09 17:15:53.070 19297 19297 D Toast   : false Toast.show in :me.weishu.epic.samples , showCount:2
01-09 17:15:53.071   330   609 I BufferQueueProducer: [me.weishu.epic.samples/me.weishu.epic.samples.MainActivity](this:0x7f7bb94c00,id:655,api:1,p:19
297,c:330) queueBuffer: fps=6.34 dur=8511.19 max=7634.04 min=12.08
01-09 17:15:53.080  1141  1385 D AppOps  : startOperation: allowing code 45 uid 10238 package me.weishu.epic.samples
01-09 17:15:53.109  1141  1159 V WindowManager: findFocusedWindow: Found new focus @ 4 = Window{ed63687 u0 me.weishu.epic.samples/me.weishu.epic.sampl
es.MainActivity}
01-09 17:15:53.127   330  1235 I BufferQueueProducer: [Toast](this:0x7f7bc07000,id:656,api:1,p:19297,c:330) connect(P): api=1 producer=(19297:me.weish
u.epic.samples) producerControlledByApp=true
01-09 17:15:55.070  1141  1141 D NotificationService: Timeout pkg=me.weishu.epic.samples callback=android.app.ITransientNotification$Stub$Proxy@d8b67d
2
01-09 17:15:55.080  1141  2610 V WindowManager: findFocusedWindow: Found new focus @ 4 = Window{ed63687 u0 me.weishu.epic.samples/me.weishu.epic.sampl
es.MainActivity}

case9：

**Comment by tiann** [comment]
@Gordon0918 闪退？还是啥

**Comment by Gordon0918** [comment]
没有闪退，提示测试为不通过，360N4，android版本6.0

**Comment by tiann** [comment]
用的是我最新的源码编译的吗？

**Comment by Gordon0918** [comment]
今天下载的最新代码，现象比较有意思 如果先测试case1，case1是通过的，case9不通过，如果先测试case9，那么case9和case1都不通过……

**Comment by tiann** [comment]
这两个case hook了相同的函数；我这测试没有问题。

能否把Build类里面的DEBUG改为true，提供下完整日志？
