### ISSUE TITLE
华为5.0 64位报错

### ISSUE THREAD

**Issue by jarno520** [tiann/epic#21]
华为5.0 64位报错，Epic类请加上21 和22版本的判断即可

01-18 19:17:18.579 5126-5126/me.weishu.epic.samples E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: me.weishu.epic.samples, PID: 5126
                                                                      java.lang.ExceptionInInitializerError
                                                                          at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:138)
                                                                          at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:194)
                                                                          at me.weishu.epic.samples.tests.returntype.VoidType.test(VoidType.java:27)
                                                                          at me.weishu.epic.samples.MainActivity$MyAdapter$1.onClick(MainActivity.java:106)
                                                                          at android.view.View.performClick(View.java:4768)
                                                                          at android.view.View$PerformClick.run(View.java:19692)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5564)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                       Caused by: java.lang.RuntimeException: Do not support this ARCH now!! API LEVEL:21
                                                                          at me.weishu.epic.art.Epic.<clinit>(Epic.java:77)
                                                                          at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:138) 
                                                                          at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:194) 
                                                                          at me.weishu.epic.samples.tests.returntype.VoidType.test(VoidType.java:27) 
                                                                          at me.weishu.epic.samples.MainActivity$MyAdapter$1.onClick(MainActivity.java:106) 
                                                                          at android.view.View.performClick(View.java:4768) 
                                                                          at android.view.View$PerformClick.run(View.java:19692) 
                                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:135) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5564) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by tiann** [comment]
5.x 的 ARM64不支持，要使用的话；使用armeabi即可。

**Comment by jarno520** [comment]
我试了下，是可以成功的，我在Epic类上加了21和22的ARM64，没有报错，能hook

**Comment by tiann** [comment]
好，那我自测下
