### ISSUE TITLE
LOLLIPOP_MR1 的VIVO X7没法跑

### ISSUE THREAD

**Issue by boycs007** [tiann/epic#27]
![image](https://user-images.githubusercontent.com/11625781/37400479-0b5268c2-27c0-11e8-9520-b86d0329ff26.png)

LOLLIPOP_MR1 的VIVO X7没法跑，8.0.0的华为mate9可以跑。

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.weishu.epic.samples, PID: 29610
                  java.lang.ExceptionInInitializerError
                      at me.weishu.epic.art.Epic.hookMethod(Epic.java:0)
                      at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:127)
                      at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:1
                      at me.weishu.epic.samples.tests.returntype.ShortType.test(ShortType.java:23)
                      at me.weishu.epic.samples.MainActivity$MyAdapter$1.onClick(MainActivity.java:106)
                      at android.view.View.performClick(View.java:4790)
                      at android.view.View$PerformClick.run(View.java:19924)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5418)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                   Caused by: java.lang.RuntimeException: Do not support this ARCH now!! API LEVEL:22
                      at me.weishu.epic.art.Epic.<clinit>(Epic.java:77)

**Comment by tiann** [comment]
Do not support this ARCH now!!

Lollipop 的64位不支持，用armeabi即可。
