### ISSUE TITLE
使用过程中会crash，不知以下堆栈，是否有解决方案

### ISSUE THREAD

**Issue by boycs007** [tiann/epic#36]
"Instr: android.support.test.runner.AndroidJUnitRunner" prio=10 tid=14 Runnable
  | group="" sCount=0 dsCount=0 flags=2 obj=0x139803f0 self=0xdcbe3a00
  | sysTid=24383 nice=-8 cgrp=default sched=0/0 handle=0xc5050970
  | state=R schedstat=( 23515859919 642456768 5804 ) utm=2280 stm=70 core=4 HZ=100
  | stack=0xc4f4e000-0xc4f50000 stackSize=1038KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 002c6aa3  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+130)
  native: #01 pc 00359273  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+202)
  native: #02 pc 00355757  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMapb+34)
  native: #03 pc 00346015  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+28)
  native: #04 pc 00345df7  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+346)
  native: #05 pc 0033a7b7  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+110)
  native: #06 pc 0033aeb3  /system/lib/libart.so (_ZN3art7Runtime7AborterEPKc+10)
  native: #07 pc 003f3419  /system/lib/libart.so (_ZN7android4base10LogMessageD1Ev+456)
  native: #08 pc 003bffa7  /system/lib/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE+250)
  native: #09 pc 003bfe7d  /system/lib/libart.so (_ZN3art12JniMethodEndEjPNS_6ThreadE+8)
  native: #10 pc 000005cb  /data/app/com.tencent.wifimanager.test-UIoa7f0RKEkioiv4ti0NbQ==/oat/arm/base.odex (Java_me_weishu_epic_art_EpicNative_compileMethod__Ljava_lang_reflect_Member_2J+146)
  at me.weishu.epic.art.EpicNative.compileMethod(Native method)
  at me.weishu.epic.art.EpicNative.compileMethod(EpicNative.java:121)
  at me.weishu.epic.art.method.ArtMethod.compile(ArtMethod.java:236)
  at me.weishu.epic.art.Epic.hookMethod(Epic.java:116)
  at me.weishu.epic.art.Epic.hookMethod(Epic.java:88)
  at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:127)
  at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:181)

**Comment by boycs007** [comment]
机型，在华为mate9 8.0系统，mate 10 pro ， google pixel 8.10，都有出现。
