### ISSUE TITLE
小米5s，android6.0不支持hook

### ISSUE THREAD

**Issue by dingjikerbo** [tiann/epic#7]
me.weishu.epic.Hook$UnsupportedException: can not backup method.
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.Hook.backUp(Hook.java:135)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.Hook.hook(Hook.java:28)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.MainActivity$2.onClick(MainActivity.java:46)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.view.View.performClick(View.java:5207)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.view.View$PerformClick.run(View.java:21177)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5458)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err: Caused by: me.weishu.epic.Hook$UnsupportedException: reflection error:
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.Hook$Reflection.call(Hook.java:147)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.Hook.backUp(Hook.java:98)
04-11 06:25:15.933 13915-13915/weishu.me.epic.test W/System.err: 	... 11 more
04-11 06:25:15.934 13915-13915/weishu.me.epic.test W/System.err: Caused by: java.lang.NoSuchMethodException: toLong []
04-11 06:25:15.934 13915-13915/weishu.me.epic.test W/System.err:     at java.lang.Class.getMethod(Class.java:624)
04-11 06:25:15.934 13915-13915/weishu.me.epic.test W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:586)
04-11 06:25:15.934 13915-13915/weishu.me.epic.test W/System.err:     at me.weishu.epic.Hook$Reflection.call(Hook.java:143)
04-11 06:25:15.934 13915-13915/weishu.me.epic.test W/System.err: 	... 12 more

**Comment by dingjikerbo** [comment]
用的java 1.8
